#!/usr/bin/env bash
set -euo pipefail

# Generate the public R4 facade from the exact github.com/google/fhir/go version
# selected by this module. Run from any directory with: go generate ./pkg/proto/r4.
root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
module=$(go env GOPATH)/pkg/mod/github.com/google/fhir/go@$(go list -m -f '{{.Version}}' github.com/google/fhir/go)
base="$module/proto/google/fhir/proto/r4/core"
out="$root/aliases_gen.go"

if [[ ! -d "$base" ]]; then
	printf 'google FHIR module not found at %s\n' "$base" >&2
	exit 1
fi

declare -A packages
packages["codes_go_proto"]="$base/codes_go_proto"
packages["datatypes_go_proto"]="$base/datatypes_go_proto"
packages["extensions_go_proto"]="$base/extensions_go_proto"
packages["valuesets_go_proto"]="$base/valuesets_go_proto"
while IFS= read -r dir; do
	packages["$(basename "$dir")"]="$dir"
done < <(find "$base/resources" -mindepth 1 -maxdepth 1 -type d -name '*_go_proto' | sort)

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
	printf '// Code generated by generate.sh; DO NOT EDIT.\n\n'
	printf 'package r4\n\n'
	printf 'import (\n'
	for key in "${!packages[@]}"; do
		alias="r4${key%_go_proto}"
		path="${packages[$key]}"
		import_path="${path#"$module/"}"
		printf '\t%s "github.com/google/fhir/go/%s"\n' "$alias" "$import_path"
	done | sort
	printf ')\n\n'
	printf 'const generatedFacadeVersion = "%s"\n\n' "$(go list -m -f '{{.Version}}' github.com/google/fhir/go)"

	for key in $(printf '%s\n' "${!packages[@]}" | sort); do
		alias="r4${key%_go_proto}"
		path="${packages[$key]}"
		# Generated files use one declaration per line; retain every exported type,
		# including nested messages, oneof wrappers, and enum value types.
		rg -H '^type [A-Z][A-Za-z0-9_]* ' "$path"/*.go \
			| sed -E 's#^[^:]+:type ([A-Z][A-Za-z0-9_]*) .*#\1#' \
			| sort -u \
			| while IFS= read -r name; do
				[[ -n "$name" ]] && printf 'type %s = %s.%s\n' "$name" "$alias" "$name"
				done
		# Re-export generated enum constants as well as their aliased types.
		{ rg -H '^\s*[A-Z][A-Za-z0-9_]*\s+[A-Z][A-Za-z0-9_]*\s*=' "$path"/*.go || true; } \
			| sed -E 's#^[^:]+:[[:space:]]*([A-Z][A-Za-z0-9_]*)[[:space:]]+.*#\1#' \
			| sort -u \
			| while IFS= read -r name; do
				[[ -n "$name" ]] && printf 'const %s = %s.%s\n' "$name" "$alias" "$name"
			done
		printf '\n'
	done
} > "$tmp"

# Duplicate aliases would make the facade fail to compile; fail generation with
# the colliding names rather than silently dropping API surface.
duplicates=$(sed -n 's/^type \([^ =]*\) =.*/\1/p' "$tmp" | sort | uniq -d)
if [[ -n "$duplicates" ]]; then
	printf 'duplicate facade aliases:\n%s\n' "$duplicates" >&2
	exit 1
fi

gofmt < "$tmp" > "$out"
